name: Use Env Text File Example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      Tes_Scripts_Folder: ${{ env.scripts }}/tes_env/
      DEV_Scripts_Folder: ${{ env.scripts }}/Dev_env/

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load Environment Variables from env.txt
        run: |
          while IFS= read -r line; do
            echo "$line" >> $GITHUB_ENV
          done < .github/workflows/env.txt

      - name: Example Step 1
        run: |
          echo "Test Scripts Folder: $Tes_Scripts_Folder"
          echo "Dev Scripts Folder: $DEV_Scripts_Folder"

      - name: Example Step 2
        run: |
          echo "Using scripts path: $scripts"
