name: Use Env File Example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load Environment Variables from env.txt
        run: |
          while IFS= read -r line; do
            echo "$line" >> $GITHUB_ENV
          done < .github/workflows/env.txt
          echo "Tes_Scripts_Folder=$scripts/tes_env/" >> $GITHUB_ENV
          echo "DEV_Scripts_Folder=$scripts/Dev_env/" >> $GITHUB_ENV

      - name: Example Step 1
        run: |
          echo "Test Scripts Folder: $Tes_Scripts_Folder"
          echo "Dev Scripts Folder: $DEV_Scripts_Folder"

      - name: Example Step 2
        run: |
          echo "Using Test Scripts Folder: $Tes_Scripts_Folder"
          echo "Using Dev Scripts Folder: $DEV_Scripts_Folder"
